name: Publish to npm

on:
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: cd ./package/ && npm ci
      - run: cd ./package/ npm run build
      - run: npm pack
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
